name: Daily Auto Commit

on:
  schedule:
    # Runs every day at 09:00 UTC (2:30 PM India)
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Commit by 24f1001363@ds.study.iitm.ac.in
        run: |
          echo "Last update: $(date -u)" > last-update.txt
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add last-update.txt
          git commit -m "Daily commit: $(date -u)" || echo "No changes to commit"
          git push
